
services:
  backend:
    image: "sjc.vultrcr.com/dongregistry/scrape_back:latest"
    container_name: news_miner
    restart: unless-stopped
    volumes:
      - ./logs:/home/node/logs
      - /etc/localtime:/etc/localtime
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 700M
        reservations:
          cpus: '0.15'
          memory: 300M
    # ports:
    #   - 5500:5500
    expose:
      - ${APP_PORT}
    env_file:
      - .env
    networks:
      - proxy

networks:
  proxy:
    external: true