---
version: '3.7'
services:
  redis:
    image: redis:7.0.15
    container_name: gpt_redis
    expose:
      - ${REDIS_PORT}
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./redis_data:/data\
    command: redis-server --requirepass ${REDIS_PASS}
    networks:
      - proxy

  backend:
    depends_on:
      - redis
    image: ${REGISTRY_URL}
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile-deploy
    container_name: news_miner
    restart: unless-stopped
    volumes:
      - ./logs:/home/node/logs
      - /etc/localtime:/etc/localtime
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 700M
        reservations:
          cpus: '0.15'
          memory: 300M
    # expose:
    #   - ${APP_PORT}
    env_file:
      - .env
    networks:
      - proxy

networks:
  proxy:
    external: true